name: hack20
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_treeview: ^0.4.1+1

uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter95: ^0.0.7
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  audioplayers: ^0.15.1

assets:

  - assets/img/du.png
  - assets/img/du1.png
  - assets/img/du2.png
  - assets/img/du3.png
  - assets/img/du4.png
  - assets/sound/dial-up-modem-01.mp3
  - assets/sound/dial-up-modem-busy.mp3